### ISSUE TITLE
Add an option to enable org-side-tree window persistent without being closed by commands like C-x 1

### ISSUE THREAD

**Issue by IceAsteroid** [localauthor/org-side-tree#10]
Is it a good idea, or just here a 'native' way to do it in emacs?

This is useful when there are several windows opened and when the user hits C-x 1, or a similar command to close all other windows, the org-side-tree can be kept open without the need to open it up again.

I wonder how treemacs or org-sidebar has this feature without being closed by C-x 1.

**Comment by localauthor** [comment]
Good idea!

This is now implemented, but it is not enabled by default.

To enable, set `org-side-tree-no-delete-other-windows` to t in your config.

**Comment by IceAsteroid** [comment]
You're the best, that's wonderful
