### ISSUE TITLE
Unable to open the selected & collapsed sub-headings for org-mode buffer by org-side-tree

### ISSUE THREAD

**Issue by IceAsteroid** [localauthor/org-side-tree#15]
Hi, greetings! @localauthor, long time no see :)

Selecting sub-headings of a heading but the corresponding heading is collapsed in the org-mode buffer, will not be able to expand the selected headings as expected. 

It's as shown below:

https://github.com/localauthor/org-side-tree/assets/90975914/bab0890b-0624-4ee8-8198-972efe131098

**Comment by localauthor** [comment]
It looks like you have outline-minor-mode subheadings inside code blocks in an org file. Is that right?

**Comment by localauthor** [comment]
Could you evaluate the following function, then try again and see if the expected behavior occurs?

```emacs-lisp
(defun org-side-tree-goto-marker (marker)
  "Go to MARKER, widen if necessary."
  (when (or (> marker (point-max))
            (< marker (point-min)))
    (widen))
  (goto-char marker)
  (outline-show-entry))
```

**Comment by IceAsteroid** [comment]
It worked. But the ending ellipsis is leftover in the end of the content


https://github.com/localauthor/org-side-tree/assets/90975914/a39824bb-ac11-42ae-b5ac-5c7ff77e6571

**Comment by localauthor** [comment]
The ellipsis stays there to indicate that there is some hidden text between that entry and the next heading. If you click on the heading "Eshell & Shell tweaaks with use of corfu", does the ellipsis stay there?

**Comment by IceAsteroid** [comment]
I used different fonts for headings and contents respectively, that might be what was confusing you.

And when I expand the heading's content via org-side-tree, there will be these ellipsis there at the end of the content.

How to remove these ellipses at the end of each content?

**Comment by localauthor** [comment]
Right, yes. The ellipsis is not there because of something that org-side-tree is doing. It is there because there is hidden text in the buffer. For example:

![Screenshot 2024-02-07 at 10 42 19](https://github.com/localauthor/org-side-tree/assets/78040295/1f57410d-a629-4f1e-9c49-9f4dba06b7de)

In this shot, see how the line numbers go from 10 (at the ellipsis) to 30 (at the next headline). That means that lines 11-29 are hidden. That is what the ellipsis is there to tell you. This is a feature of org-mode and outline-(minor-)mode, not a feature of org-side-tree.

**Comment by IceAsteroid** [comment]
Sincerely sorry for this, really doubtful of my recent mental state, which made me neglect this apparent thing in testing the snippet that you posted.

Yes, it's indeed the case, which hides the same level headings & their contents.

Now, the question becomes, is it possible to make the same level headings which are under the same parent heading, show up while being collapsed, and also to make the parent heading's content show up?

It's for the sake of providing better convenience to edit things across previous & next headings and their contents. For example:  

Like follows:
Fully expanded of the first-level heading for all its content including sub-headings for demonstration of what it looks like originally.
![org-side-tree-expand-4 jpg](https://github.com/localauthor/org-side-tree/assets/90975914/c05fc5a7-f714-42f0-bbe3-4b778d3187fd)

Example 1: Demo of what's intended to be for expanding a second-level heading:
![org-side-tree-expand-2 jpg](https://github.com/localauthor/org-side-tree/assets/90975914/3df59154-a8f6-41db-918d-40d5ae9fb117)

Example 2: Demo of what's intended to be for expanding a third-level heading:
![org-side-tree-expand-3 jpg](https://github.com/localauthor/org-side-tree/assets/90975914/b0bb9e28-ce20-431b-9432-09834db349f8)

**Comment by IceAsteroid** [comment]
The above post was just for suggestion, there might be a better option

**Comment by localauthor** [comment]
I'm not sure how to generalize your suggestion enough to make it part of the the package, but you could always add advice to your own config, to open whichever headings you want after using `org-side-tree-jump`.

For example:

```elisp
(defun my/org-side-tree-open-parent (_)
  (save-excursion
    (outline-up-heading 1)
    (outline-show-entry)))

(advice-add 'org-side-tree-jump :after 'my/org-side-tree-open-parent)```

**Comment by IceAsteroid** [comment]
Good news!

I have implemented it as it's easy enough and not beyond my elisp pour skills

Here's the code:
```
  (defun my/org-side-tree-open-parent (_)
    (save-excursion
      (outline-hide-other))
    (save-excursion
      ;;to show all sub-headings & contents of the heading selected in
      ;;org-side-tree, after run "outline-hide-other", since it also
      ;;closes sub-headings
      (outline-show-children))
    (save-excursion
      (while (outline-up-heading 1)
	(outline-show-entry)
	(outline-show-children)))
    )
  (advice-add 'org-side-tree-jump :after 'my/org-side-tree-open-parent)
```

which shows the sibling headings but not their contents and also shows the father headings' contents respectively.

However, I'm afraid that the part, say part A

```
    (save-excursion
      (while (outline-up-heading 1)
	(outline-show-entry)
	(outline-show-children)))
```

will keep running endless in the background, since when the part, say part B

```
    (save-excursion
      ;;to show all sub-headings & contents of the heading selected in
      ;;org-side-tree, after run "outline-hide-other", since it also
      ;;closes sub-headings
      (outline-show-children))
```

was put after part A, it didn't take effect at all. And Emacs complaints in the echo area like "Already at top level of the outline".

Is there a better way to do this?

Here's what it does:

https://github.com/localauthor/org-side-tree/assets/90975914/a2a2ea1b-2cdc-4970-a3c5-a8df3353811e

**Comment by IceAsteroid** [comment]
I got ideas to solve it, I'll try them first, sorry for disturbing
