### ISSUE TITLE
Rendering headers with links

### ISSUE THREAD

**Issue by okomestudio** [localauthor/org-side-tree#2]
This is a suggestion/feature request.

When headers contain links, their markups are rendered as is. For example, see the following screenshot:

![image](https://github.com/localauthor/org-side-tree/assets/2257159/4baea767-1fb8-4e1b-8ef2-c628fd452b7f)

This doesn't seem useful to me. Wouldn't it be better to either remove the links or render just the link descriptions?

**Comment by localauthor** [comment]
Thanks so much for the suggestion! This should be fixed in the latest commit. Let me know if it doesn't work as expected.

**Comment by okomestudio** [comment]
I've tried and confirmed that it's working as described in OP. Thank you very much for such a quick response and fix, and also making the package available!

**Comment by localauthor** [comment]
Reverted the commit for now, as it raised some foreseen issues. Working on a different fix.

**Comment by localauthor** [comment]
Ok, hopefully this does it! 🤞

**Comment by okomestudio** [comment]
Still ｗorks for me, with current HEAD. Thanks.
